#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : swupd-client-pre-release
Version  : 81b4401509f06483ac91057daa2ddf4a9d52a1c3
Release  : 6
URL      : https://github.com/clearlinux/swupd-client/archive/81b4401509f06483ac91057daa2ddf4a9d52a1c3.tar.gz
Source0  : https://github.com/clearlinux/swupd-client/archive/81b4401509f06483ac91057daa2ddf4a9d52a1c3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: swupd-client-pre-release-bin = %{version}-%{release}
Requires: swupd-client-pre-release-license = %{version}-%{release}
BuildRequires : bzip2-dev
BuildRequires : docutils
BuildRequires : pkgconfig(bsdiff)
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(libarchive)
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(zlib)
BuildRequires : systemd-dev
Patch1: always-run-ldconfig.patch

%description
The swupd-client package provides a reference implementation of a software
update client which performs file level updates of an OS, preferentially
using binary deltas whenever possible for efficiency under an assumption
that the OS develops with a release process aimed at rapidly deploying
small incremental changes.

%package bin
Summary: bin components for the swupd-client-pre-release package.
Group: Binaries
Requires: swupd-client-pre-release-license = %{version}-%{release}

%description bin
bin components for the swupd-client-pre-release package.


%package license
Summary: license components for the swupd-client-pre-release package.
Group: Default

%description license
license components for the swupd-client-pre-release package.


%prep
%setup -q -n swupd-client-81b4401509f06483ac91057daa2ddf4a9d52a1c3
cd %{_builddir}/swupd-client-81b4401509f06483ac91057daa2ddf4a9d52a1c3
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1578948242
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%autogen --disable-static --disable-tests \
--enable-signature-verification \
--with-contenturl=https://cdn.download.clearlinux.org/update/ \
--with-versionurl=https://cdn.download.clearlinux.org/update/ \
--with-formatid=29 \
--with-fallback-capaths=/usr/share/ca-certs/.prebuilt-store/anchors \
--with-post-update=/usr/bin/update-helper \
--with-build-number=%{release} \
--enable-third-party
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1578948242
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/swupd-client-pre-release
cp %{_builddir}/swupd-client-81b4401509f06483ac91057daa2ddf4a9d52a1c3/COPYING %{buildroot}/usr/share/package-licenses/swupd-client-pre-release/f5b8c6b890f2c7664954577396afb1fed9aa550f
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/bin/verifytime
rm -f %{buildroot}/usr/lib/systemd/system/check-update.service
rm -f %{buildroot}/usr/lib/systemd/system/check-update.timer
rm -f %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/check-update.timer
rm -f %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/swupd-update.timer
rm -f %{buildroot}/usr/lib/systemd/system/swupd-update.service
rm -f %{buildroot}/usr/lib/systemd/system/swupd-update.timer
rm -f %{buildroot}/usr/lib/systemd/system/verifytime.service
rm -f %{buildroot}/usr/share/defaults/etc/profile.d/50-swupd.bash
rm -f %{buildroot}/usr/share/defaults/swupd/config
rm -f %{buildroot}/usr/share/man/man1/swupd.1
rm -f %{buildroot}/usr/share/man/man4/check-update.service.4
rm -f %{buildroot}/usr/share/man/man4/check-update.timer.4
rm -f %{buildroot}/usr/share/man/man4/swupd-update.service.4
rm -f %{buildroot}/usr/share/man/man4/swupd-update.timer.4
rm -f %{buildroot}/usr/share/man/man4/update-triggers.target.4
rm -f %{buildroot}/usr/share/man/man7/swupd-alias.7
rm -f %{buildroot}/usr/share/polkit-1/actions/org.clearlinux.swupd.policy
rm -f %{buildroot}/usr/share/polkit-1/rules.d/org.clearlinux.swupd.rules
rm -f %{buildroot}/usr/share/zsh/site-functions/_swupd
## install_append content
mv %{buildroot}/usr/bin/swupd %{buildroot}/usr/bin/swupd-pre-release
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/swupd-pre-release

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/swupd-client-pre-release/f5b8c6b890f2c7664954577396afb1fed9aa550f
